### PR TITLE
Set RepositoryUrl/ProjectUrl to github repo.

### PR DESCRIPTION
**Pull request by mikem8361**
Needed to upload to nuget.

### CODE REVIEW

**Comment by tmat** [comment]
This should be set by SourceLink package. Do you have SourceLink disabled? I remember there were some issues with SourceLink on some Linux distros, but those were fixed.

**Comment by mikem8361** [comment]
RepositoryUrl was set to the internal mirror'ed DotNet-SymStore-Trusted repo.  This repo also still uses Roslyn-Toolset.

**Comment by mikem8361** [comment]
I don't have SourceLink disabled by the way.

**Comment by mikem8361** [comment]
When I tried to upload the latest dotnet-symbol tool package to nuget it complained about the ProjectUrl. That is where I saw that the Repo url was the internal one.

**Comment by tmat** [comment]
I see. OK.

**Pull request merged**
