### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@mikem8361 The Linux build is failing because .sh files are not marked executable. Needs:

```
git update-index --chmod=+x file.sh
```

**Comment by mikem8361** [comment]
Are you saying I needed to add the execute bit before commiting the *.sh files?

**Comment by tmat** [comment]
I merged your PR. Now it fails to build Microsoft.FileFormats.csproj which targets `net45` and `netstandard1.5`. Any reason why we need to target `net45`. We can do so, that's not a problem, just wondering if we need to.

**Comment by mikem8361** [comment]
Yes, it needs to build for net45 because the DotNet-SymUploader build task needs to build for net45.

**Comment by tmat** [comment]
OK, I added `<UsingToolNetFrameworkReferenceAssemblies>true</UsingToolNetFrameworkReferenceAssemblies>` to fetch the package containing reference assemblies for netfx

**Comment by mikem8361** [comment]
I'm working on the Linux failures.

**Pull request merged**
