### PR TITLE
Upgrade to the latest RoslynToolSet

### PR DESCRIPTION
**Pull request by mikem8361**
Update all the build and project files to use RoslynToolSet 1.0.0-beta2-62810-01 and dotnet cli 2.1.101.

### CODE REVIEW

**Comment by tmat** [comment]
test ci please

**Comment by mikem8361** [comment]
@dotnet test ci

**Comment by mikem8361** [comment]
@tmat the ci builds are broken until I check in the new netci.groovy.

**Comment by tmat** [comment]
yes, let's merge.

**Pull request merged**
