### PR TITLE
Don't run Linux/Mac in official build

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mikem8361** [comment]
Why? To save resources?

**Comment by mmitche** [comment]
We have to switch the pool usage in the official build to use 1ES pools, and these are already run in the rolling public CI.

**Review by mikem8361 — APPROVED** [review]

**Comment by mmitche** [comment]
Official build test: https://dev.azure.com/dnceng/internal/_build/results?buildId=1584607&view=results

**Comment by hoyosjs** [comment]
@mikem8361 are there any tests that make it worth to build this outside of windows? AS far as I know, most of the tests run on top of blobs

**Review by hoyosjs — APPROVED** [review]

**Comment by mikem8361** [comment]
All the testing is the same (run against test assets checked in) regardless of the platform.  So the official build doesn't need Linux/MacOS but I hope our check in CI will continue to build/test on them.

**Comment by mmitche** [comment]
> All the testing is the same (run against test assets checked in) regardless of the platform. So the official build doesn't need Linux/MacOS but I hope our check in CI will continue to build/test on them.

Yes that will be the case.

**Pull request merged**
