### PR TITLE
Misc fixes and changes.

### PR DESCRIPTION
**Pull request by mikem8361**
Fixed Path.GetFileName on Windows paths running on Linux.

Fixed NugetSymbolServer project.

Fixed issue #83 and GitHub security alert about Microsoft.AspNetCore.Mvc.

changed dotnet-symbol version to 1.0.1.

Added default cache.

The same location as the SOS symbol server support.

$HOME/.dotnet/symbolcache on xplat.
%USERPROFILE%\.dotnet\symbolcache on Windows.

### CODE REVIEW

**Comment by tmat** [comment]
@mikem8361 Why should the default symbol cache be specific to .dotnet?
I would assume it would be shared across all frameworks and all debuggers on the machine.

We have recently discussed setting the default primary symbol cache to `%USERPROFILE%\.nuget\symbols`, since NuGet.org now supports symbol servers and we want it to be able to restore symbols to a local symbol cache (something like `nuget.exe restore -symbols` or `dotnet restore --symbols`).

@chuckries @anangaur @rrelyea

**Comment by mikem8361** [comment]
Because this tool is dotnet and that is where the symbol download now in SOS caches. These tools have nothing to with nuget so that cache doesn't make any sense. $HOME/.dotnet/tool is where global tools like dotnet-symbol are installed.


-------- Original message --------

**Comment by tmat** [comment]
I don't think it make sense for customers to have to manage one symbol cache for each tool they use. 
Besides, if the tools don't know of each other's cache then they will download the same symbol file multiple times wasting bandwidth and space on disk. 

Maybe `%USERPROFILE%\.nuget\symbols` is not the right place, maybe it's `%USERPROFILE%\.symbols`, but I believe we need a single directory to store symbols, not 3:  `%USERPROFILE%\AppData\Local\Temp\SymbolCache` (VS debugger), `%USERPROFILE%.dotnet\symbolcache` (dotnet-symbol),  `%USERPROFILE%\.nuget\symbols` (NuGet).

**Comment by mikem8361** [comment]
You have a good point. windbg/cdb also have yet another cache usually in %ProgramData%\dbg\sym.

I would be fine with %USERPROFILE%\.symbols on Windows and $HOME/.symbols on xplat.

**Comment by gregg-miskelly** [comment]
I don't think VS can change its default. So if you think it is useful to share the same location as VS, you should use %USERPROFILE%\AppData\Local\Temp\SymbolCache on Windows.

**Comment by tmat** [comment]
@gregg-miskelly Why can't VS change the default?

**Comment by mikem8361** [comment]
Ok, I think we should use the VS directory on Windows and my original xplat directory.  On xplat, I think it does make sense for VS, dotnet-symbol, SOS and nuget to put the ".dotnet" directory since these are dotnet or dotnet related symbols. I also think on xplat it should be lowercase:

Windows: %USERPROFILE%\AppData\Local\Temp\SymbolCache
Linux/MacOS: $HOME/.dotnet/symbolcache

@noahfalk, @tmat, @gregg-miskelly

**Comment by mikem8361** [comment]
@gregg-miskelly does VS use the "TEMP" env var to get to this directory or does it explicitly %USERPROFILE%\AppData\Local\Temp\SymbolCache?

**Comment by mikem8361** [comment]
@gregg-miskelly one more question: do you mind the directory being in $HOME/.dotnet for vsdbg? There isn't any native debugging for VSCode yet, but would it want to use a different path?

**Comment by tmat** [comment]
Should't it be `symbol-cache` on linux? Not sure what the general convention is, but `symbolcache` is less readable.

**Comment by anangaur** [comment]
We should all agree on one symbols folder - something that NuGet can also use in future while pre-fetching symbols (with an option) during restore or with any other command. 

What does dotnet-symbol do? Is it used for pre-caching symbols? For what?

**Comment by gregg-miskelly** [comment]
>@gregg-miskelly does VS use the "TEMP" env var to get to this directory or does it explicitly %USERPROFILE%\AppData\Local\Temp\SymbolCache?

The VS code will call GetTempPath, and then append the "SymbolCache" directory to it. I would need to check the implementation, but I believe GetTempPath will always return the environment variable if it is present (which obviously it is 99.999% of the time).

> @gregg-miskelly one more question: do you mind the directory being in $HOME/.dotnet for vsdbg? There isn't any native debugging for VSCode yet, but would it want to use a different path?

To be clear: I assume you mean something like `$HOME/.dotnet/symbolcache` (or `$HOME/.dotnet/symbol-cache` linke Tomas's suggestion) and not directly in the '.dotnet' folder.

Personally I think it makes sense on Linux to have a shared symbol cache directory for the various .NET products, and if symbol server ever catches on with a non-.NET Linux audience through the VS/VS Code C++ then we can use a different cache directory. I don't think it makes sense to pick a more general purpose directory when may never have a solution in the C++ space.

**Comment by mikem8361** [comment]
dotnet-symbol cracks core dumps, mini-dumps and other binaries and downloads the symbols for them from the Microsoft symbol server.

lldb doesn’t download symbols so this is to fill in the gap allowing all the .NET Core runtime symbols and binaries needed to debug a core dump be downloaded.

See https://github.com/dotnet/symstore/tree/master/src/dotnet-symbol#symbol-downloader-dotnet-cli-extension for more details.

Do you have any objections with “.dotnet” being in the symbol cache path? This also assumes you agree will the layout and indexing used in the cache by VS, dbgeng and these .dotnet tools. The specs for symbol server indexing are here: https://github.com/dotnet/symstore/tree/master/docs/specs#table-of-contents.

The cache layout is <file-name>/<index>/<file-name> all lowercased.

**Comment by mikem8361** [comment]
Yes, I meant $HOME/.dotnet/symbolcache on Linux for vsdbg.

**Pull request merged**
