### PR TITLE
Upgrade to RoslynTools.RepoToolset 1.0.0-beta2-63021-06.

### PR DESCRIPTION
**Pull request by mikem8361**

### CODE REVIEW

**Comment by tmat** [comment]
What's the problem with the newer version?

**Comment by mikem8361** [comment]
I get the below errors in symstore and DotNet-SymUploader repos when I went to latest (1.0.0-beta2-63021-06) or 1.0.0-beta2-63011-08.


2018-06-27T23:08:08.5335936Z   Restore completed in 2.34 min for E:\A\_work\37\s\src\NugetSymbolServer\NugetSymbolServer.csproj.
2018-06-27T23:08:08.6263577Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:08.8301596Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:08.8332682Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:08.9277432Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:08.9304015Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:08.9784970Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:09.0538590Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:09.0950569Z   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
2018-06-27T23:08:09.2679303Z E:\A\_work\37\s\.packages\microsoft.sourcelink.common\1.0.0-beta-63001-01\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'E:\A\_work\37\s\' [E:\A\_work\37\s\src\Microsoft.FileFormats\Microsoft.FileFormats.csproj]
2018-06-27T23:08:09.3058026Z E:\A\_work\37\s\.packages\microsoft.sourcelink.common\1.0.0-beta-63001-01\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'E:\A\_work\37\s\' [E:\A\_work\37\s\src\Microsoft.FileFormats\Microsoft.FileFormats.csproj]
2018-06-27T23:08:09.3969811Z E:\A\_work\37\s\.packages\microsoft.sourcelink.common\1.0.0-beta-63001-01\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'E:\A\_work\37\s\' [E:\A\_work\37\s\src\NugetSymbolServer\NugetSymbolServer.csproj]
2018-06-27T23:08:09.4268455Z
2018-06-27T23:08:09.4281316Z Build FAILED.
2018-06-27T23:08:09.4283832Z
2018-06-27T23:08:09.4287098Z E:\A\_work\37\s\.packages\microsoft.sourcelink.common\1.0.0-beta-63001-01\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'E:\A\_work\37\s\' [E:\A\_work\37\s\src\Microsoft.FileFormats\Microsoft.FileFormats.csproj]
2018-06-27T23:08:09.4290687Z E:\A\_work\37\s\.packages\microsoft.sourcelink.common\1.0.0-beta-63001-01\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'E:\A\_work\37\s\' [E:\A\_work\37\s\src\Microsoft.FileFormats\Microsoft.FileFormats.csproj]
2018-06-27T23:08:09.4294549Z E:\A\_work\37\s\.packages\microsoft.sourcelink.common\1.0.0-beta-63001-01\build\Microsoft.SourceLink.Common.targets(60,5): error : SourceRoot.SourceLinkUrl is empty: 'E:\A\_work\37\s\' [E:\A\_work\37\s\src\NugetSymbolServer\NugetSymbolServer.csproj]
2018-06-27T23:08:09.4461240Z     0 Warning(s)
2018-06-27T23:08:09.4461905Z     3 Error(s)
2018-06-27T23:08:09.4462712Z
2018-06-27T23:08:09.4463601Z Time Elapsed 00:02:25.00
2018-06-27T23:08:09.5102274Z Build log: E:\A\_work\37\s\eng\common\..\..\artifacts\Release\log\Build.binlog
2018-06-27T23:08:09.7403676Z ##[error]Process completed with exit code 1.
2018-06-27T23:08:09.7431134Z ##[section]Finishing: Run script eng\common\CIBuild.cmd

**Comment by tmat** [comment]
I think you just need to set property `<SourceLinkProvider>Vsts.Git</SourceLinkProvider>`. The default is 'GitHub` which is why it fails in VSTS.

**Comment by mikem8361** [comment]
It has to work on both.  Most of my repos have a public github repo and a internal VSTS mirror.  DotNet-SymUploader is VSTS only and that will work. But symstore and diagnostics repo’s are both.

**Comment by mikem8361** [comment]
The default doesn’t seem to be GitHub even though RepositoryInfo.targets sets it to that if empty.  When I explicitly set it to GitHub in the symstore repo, it works locally and probably in the CI jobs but I’m not sure what condition to use to set it to Vsts.Git for the internal job.

Setting it to Vsts.Git for DotNet-SymUploader works great.

**Comment by tmat** [comment]
You can add multiple providers. Maybe I should change the `SourceLinkProvider` to item group. For now you can set `SourceLinkProvider` to `GitHub` and also add  

```xml
<PackageReference Include="Microsoft.SourceLink.Vsts.Git" Version="$(MicrosoftSourceLinkVersion)" PrivateAssets="all" />
```

SourceLink will determine which one to use based on the remote origin url.

**Comment by tmat** [comment]
Adding it to `Directory.Build.props` file in the repo root will do.

**Pull request merged**
